image: node:lts-alpine3.9

stages:
  - pre-release
  - build
  - release

pre-release:
  stage: pre-release
  artifacts:
    paths:
    - version
  before_script:
    - apk add --no-cache git
    - npm i -g @commitlint/cli @commitlint/config-conventional
    - commitlint --from=$CI_BUILD_BEFORE_SHA
  script:
    - npm install @semantic-release/exec
                  @semantic-release/changelog
                  @semantic-release/gitlab
                  @semantic-release/git
    - npx semantic-release --dry-run

build:
  stage: build
  artifacts:
    paths:
    - version
  script:
    - echo "Version -> $(cat version)"

release:
  stage: release
  script:
    - apk add --no-cache git
    - npm install @semantic-release/exec
                  @semantic-release/changelog
                  @semantic-release/gitlab
                  @semantic-release/git
    - npx semantic-release
