name: CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js (12.16.2)
      uses: actions/setup-node@v1
      with:
        node-version: '12.16.2'

    - name: Install Packages
      run: npm install -D @semantic-release/exec @semantic-release/changelog @semantic-release/github @semantic-release/git

    - name: Run Semantic Release
      run: npx semantic-release
      env:
        GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GH_TOKEN }}
