name: CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    # if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12'

    - name: get commit message
      run: |
          echo ::set-env name=commitmsg::$(git log --format=%B -n 1 ${{ github.event.after }})
    - name: Install commitlint
      run : npm i -g @commitlint/cli @commitlint/config-conventional
    - name: Validate last commit
      run : echo $commitmsg | commitlint

    - name: Install semantic release packages
      run: |
          npm install -D @semantic-release/exec \
                         @semantic-release/changelog \
                         @semantic-release/github \
                         @semantic-release/git

    - name: Run Semantic Release
      run: npx semantic-release
      env:
        GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GH_TOKEN }}
